import crypto from 'node:crypto';
import dns from 'node:dns/promises';
import net from 'node:net';
import os from 'node:os';
import fs from 'node:fs/promises';
import { registerCommand } from '../../lib/core/registry.js';
import { db } from '../../lib/core/database.js';
import { config } from '../../lib/config.js';
import { contextInfo, unwrapMessage } from '../../lib/utils/message.js';
import { encryptVaultText, decryptVaultText } from '../../lib/services/vault.js';

const safeText = (v, n=500) => String(v || '').replace(/[\r\0]/g,' ').trim().slice(0,n);
const id8 = () => crypto.randomBytes(4).toString('hex');
const fmtBytes = (n) => { n=Number(n)||0; const u=['B','KB','MB','GB','TB']; let i=0; while(n>=1024&&i<u.length-1){n/=1024;i++;} return `${n.toFixed(i?1:0)} ${u[i]}`; };

function parseHm(value) {
  const m=String(value||'').match(/^([01]?\d|2[0-3]):([0-5]\d)$/); if(!m)return null; return `${String(Number(m[1])).padStart(2,'0')}:${m[2]}`;
}
function sessionReplyBucket(ctx){ return db.savedReplies(ctx.sessionId); }

registerCommand({ name:'reminders', aliases:['reminderlist'], category:'productivity', description:'List your pending reminders', async run(ctx){ const rows=db.data.reminders.filter(r=>!r.sent&&r.sessionId===ctx.sessionId&&r.user===ctx.sender).sort((a,b)=>a.at-b.at).slice(0,30); await ctx.reply(rows.length?rows.map((r,i)=>`${i+1}. ${r.id.slice(0,8)} • ${new Date(r.at).toLocaleString('en-PK',{timeZone:config.timezone})}\n   ${r.text}`).join('\n'):'No pending reminders.'); } });
registerCommand({ name:'delreminder', aliases:['reminderdel'], category:'productivity', description:'Delete one of your pending reminders by ID', usage:'delreminder ab12cd34', async run(ctx){ const q=safeText(ctx.args[0],40); const i=db.data.reminders.findIndex(r=>!r.sent&&r.sessionId===ctx.sessionId&&r.user===ctx.sender&&String(r.id).startsWith(q)); if(i<0)return ctx.reply('Reminder not found. Use .reminders to see IDs.'); db.data.reminders.splice(i,1); await db.save(); await ctx.reply('Reminder deleted.'); } });

registerCommand({ name:'todo', category:'productivity', description:'One-command personal todo manager', usage:'todo add|list|done|del|clear ...', async run(ctx){ const action=String(ctx.args[0]||'list').toLowerCase(); ctx.user.todos ||= []; if(action==='list'){return ctx.reply(ctx.user.todos.length?ctx.user.todos.map((t,i)=>`${i+1}. [${t.done?'x':' '}] ${t.text}`).join('\n'):'Your todo list is empty.');} if(action==='add'){const text=safeText(ctx.args.slice(1).join(' '),300);if(!text)return ctx.reply(`Usage: ${ctx.prefix}todo add Finish task`);if(ctx.user.todos.length>=50)throw new Error('Todo limit reached (50).');ctx.user.todos.push({text,done:false,createdAt:Date.now()});await db.save();return ctx.reply(`Todo #${ctx.user.todos.length} added.`);} const i=Number(ctx.args[1])-1; if(['done','del'].includes(action)&&(!Number.isInteger(i)||!ctx.user.todos[i]))return ctx.reply('Provide a valid todo number.'); if(action==='done'){ctx.user.todos[i].done=!ctx.user.todos[i].done;await db.save();return ctx.reply(`Todo #${i+1}: ${ctx.user.todos[i].done?'done':'open'}.`);} if(action==='del'){ctx.user.todos.splice(i,1);await db.save();return ctx.reply('Todo deleted.');} if(action==='clear'){const mode=String(ctx.args[1]||'done').toLowerCase();ctx.user.todos=mode==='all'?[]:ctx.user.todos.filter(t=>!t.done);await db.save();return ctx.reply(`Todo list cleaned (${mode==='all'?'all':'done'}).`);} return ctx.reply(`Usage: ${ctx.prefix}todo add|list|done|del|clear`); } });

registerCommand({ name:'birthday', aliases:['bday'], category:'productivity', description:'Save annual birthday reminders for this chat', usage:'birthday add Name | 2000-05-10', async run(ctx){ const action=String(ctx.args[0]||'list').toLowerCase(); if(action==='list'){const rows=db.data.birthdays.filter(x=>x.sessionId===ctx.sessionId&&x.chat===ctx.chat);return ctx.reply(rows.length?rows.map(x=>`${x.id} • ${x.name} • ${x.date.slice(5)}`).join('\n'):'No birthdays saved for this chat.');} if(action==='del'){const id=safeText(ctx.args[1],20);const before=db.data.birthdays.length;db.data.birthdays=db.data.birthdays.filter(x=>!(x.sessionId===ctx.sessionId&&x.chat===ctx.chat&&x.id===id));await db.save();return ctx.reply(before===db.data.birthdays.length?'Birthday not found.':'Birthday deleted.');} if(action==='add'){const raw=ctx.args.slice(1).join(' ');const [name,date]=raw.split('|').map(x=>x.trim());if(!name||!/^\d{4}-\d{2}-\d{2}$/.test(date||''))return ctx.reply(`Usage: ${ctx.prefix}birthday add Ali | 2000-05-10`);const d=new Date(`${date}T00:00:00Z`);if(Number.isNaN(d.getTime()))throw new Error('Invalid birthday date.');const row={id:id8(),sessionId:ctx.sessionId,chat:ctx.chat,user:ctx.sender,name:safeText(name,80),date,lastSentYear:null};db.data.birthdays.push(row);await db.save();return ctx.reply(`🎂 Birthday saved • ${row.id}\n${row.name} • ${row.date}`);} return ctx.reply(`Usage: ${ctx.prefix}birthday add|list|del`); } });

registerCommand({ name:'event', aliases:['eventcountdown'], category:'productivity', description:'Save/list event countdowns and get notified at event time', usage:'event add Launch | 2026-12-31T20:00:00+05:00', async run(ctx){ const action=String(ctx.args[0]||'list').toLowerCase(); if(action==='list'){const rows=db.data.events.filter(x=>x.sessionId===ctx.sessionId&&x.chat===ctx.chat&&!x.sent).sort((a,b)=>a.at-b.at);return ctx.reply(rows.length?rows.map(x=>{const ms=x.at-Date.now(),hrs=Math.floor(Math.abs(ms)/3600000);return `${x.id} • ${x.name}\n   ${new Date(x.at).toLocaleString('en-PK',{timeZone:config.timezone})} • ${ms>=0?`${hrs}h left`:'due'}`}).join('\n'):'No pending events.');} if(action==='del'){const id=safeText(ctx.args[1],20);const before=db.data.events.length;db.data.events=db.data.events.filter(x=>!(x.sessionId===ctx.sessionId&&x.chat===ctx.chat&&x.id===id));await db.save();return ctx.reply(before===db.data.events.length?'Event not found.':'Event deleted.');} if(action==='add'){const [name,when]=ctx.args.slice(1).join(' ').split('|').map(x=>x.trim());const d=new Date(when||'');if(!name||Number.isNaN(d.getTime())||d.getTime()<=Date.now())return ctx.reply(`Usage: ${ctx.prefix}event add Launch | 2026-12-31T20:00:00+05:00`);const row={id:id8(),sessionId:ctx.sessionId,chat:ctx.chat,user:ctx.sender,name:safeText(name,100),at:d.getTime(),sent:false};db.data.events.push(row);await db.save();return ctx.reply(`📅 Event saved • ${row.id}\n${row.name}\n${d.toLocaleString('en-PK',{timeZone:config.timezone})}`);} return ctx.reply(`Usage: ${ctx.prefix}event add|list|del`); } });

registerCommand({ name:'vault', category:'owner', ownerOnly:true, description:'Encrypted-at-rest private owner note vault', usage:'vault set|get|list|del key ...', async run(ctx){ db.data.vault ||= {}; const bucket=(db.data.vault[ctx.sessionId] ||= {}); const action=String(ctx.args[0]||'list').toLowerCase(); if(action==='list')return ctx.reply(Object.keys(bucket).length?`🔐 Vault keys\n${Object.keys(bucket).map(k=>`• ${k}`).join('\n')}`:'Vault is empty.'); const key=safeText(ctx.args[1],50).toLowerCase(); if(!key)return ctx.reply(`Usage: ${ctx.prefix}vault set secret text | get secret | del secret | list`); if(action==='set'){const text=ctx.args.slice(2).join(' ').trim();if(!text)return ctx.reply('Provide vault text.');bucket[key]=await encryptVaultText(text.slice(0,5000));await db.save();return ctx.reply('🔐 Vault entry encrypted and saved.');} if(action==='get'){if(!bucket[key])return ctx.reply('Vault key not found.');return ctx.reply(`🔐 *${key}*\n${await decryptVaultText(bucket[key])}`);} if(action==='del'){delete bucket[key];await db.save();return ctx.reply('Vault entry deleted.');} return ctx.reply(`Usage: ${ctx.prefix}vault set|get|list|del`); } });

registerCommand({ name:'replyadd', aliases:['savereply'], category:'owner', ownerOnly:true, description:'Create a saved quick-reply command', usage:'replyadd payment | Send payment to...', async run(ctx){ const [key,...rest]=ctx.argText.split('|');const name=safeText(key,30).toLowerCase().replace(/[^a-z0-9_-]/g,'');const text=safeText(rest.join('|'),3000);if(!name||!text)return ctx.reply(`Usage: ${ctx.prefix}replyadd payment | Your reply text`);sessionReplyBucket(ctx)[name]=text;await db.save();await ctx.reply(`Saved reply: ${ctx.prefix}${name}`);} });
registerCommand({ name:'replydel', category:'owner', ownerOnly:true, description:'Delete a saved quick-reply command', usage:'replydel payment', async run(ctx){const name=safeText(ctx.args[0],30).toLowerCase();delete sessionReplyBucket(ctx)[name];await db.save();await ctx.reply('Saved reply removed.');} });
registerCommand({ name:'replylist', category:'owner', ownerOnly:true, description:'List saved quick-reply commands', async run(ctx){const keys=Object.keys(sessionReplyBucket(ctx));await ctx.reply(keys.length?`⚡ Saved replies\n${keys.map(k=>`${ctx.prefix}${k}`).join('\n')}`:'No saved replies.');} });
registerCommand({ name:'reply', aliases:['quickreply'], category:'productivity', description:'Send one of the owner configured saved replies', usage:'reply payment', async run(ctx){const name=safeText(ctx.args[0],30).toLowerCase();const text=sessionReplyBucket(ctx)[name];await ctx.reply(text||`Saved reply not found. Use ${ctx.prefix}replylist if you are the owner.`);} });

registerCommand({ name:'quiet', aliases:['quiethours'], category:'owner', ownerOnly:true, description:'Pause automatic reactions/replies during a daily time window', usage:'quiet 01:00 07:00 | quiet off', async run(ctx){const first=String(ctx.args[0]||'').toLowerCase();ctx.sessionSettings.quietHours ||= {enabled:false,start:'01:00',end:'07:00'};if(first==='off'){ctx.sessionSettings.quietHours.enabled=false;await db.save();return ctx.reply('🌙 Quiet hours OFF.');}if(first==='on'){ctx.sessionSettings.quietHours.enabled=true;await db.save();return ctx.reply(`🌙 Quiet hours ON • ${ctx.sessionSettings.quietHours.start}-${ctx.sessionSettings.quietHours.end}`);}const start=parseHm(first),end=parseHm(ctx.args[1]);if(!start||!end)return ctx.reply(`Usage: ${ctx.prefix}quiet 01:00 07:00 | quiet on|off`);ctx.sessionSettings.quietHours={enabled:true,start,end};await db.save();await ctx.reply(`🌙 Quiet hours ON • ${start}-${end}`);} });
registerCommand({ name:'away', aliases:['awaymsg'], category:'owner', ownerOnly:true, description:'Set a rate-limited away auto-reply for private chats', usage:'away on I will reply soon | away off', async run(ctx){const action=String(ctx.args[0]||'').toLowerCase();ctx.sessionSettings.away ||= {enabled:false,text:''};if(action==='off'){ctx.sessionSettings.away.enabled=false;await db.save();return ctx.reply('Away reply OFF.');}if(action==='on'){const text=safeText(ctx.args.slice(1).join(' '),1000)||ctx.sessionSettings.away.text||'I am currently away.';ctx.sessionSettings.away={enabled:true,text};await db.save();return ctx.reply(`Away reply ON:\n${text}`);}return ctx.reply(`Usage: ${ctx.prefix}away on your message | ${ctx.prefix}away off`);} });
registerCommand({ name:'afk', category:'owner', ownerOnly:true, description:'Turn on AFK mode with an optional reason', usage:'afk meeting', async run(ctx){const reason=safeText(ctx.argText,500)||'Away for a while';ctx.sessionSettings.afk={enabled:true,reason};await db.save();await ctx.reply(`💤 AFK ON • ${reason}\nUse ${ctx.prefix}back when you return.`);} });
registerCommand({ name:'back', aliases:['afkoff'], category:'owner', ownerOnly:true, description:'Turn off AFK mode', async run(ctx){ctx.sessionSettings.afk={enabled:false,reason:''};await db.save();await ctx.reply('🟢 AFK OFF • welcome back.');} });
registerCommand({ name:'reactword', aliases:['reactionrule'], category:'owner', ownerOnly:true, description:'React with a chosen emoji when incoming text contains a word', usage:'reactword add love ❤️', async run(ctx){ctx.sessionSettings.reactionRules ||= {};const action=String(ctx.args[0]||'list').toLowerCase();if(action==='list'){const rows=Object.entries(ctx.sessionSettings.reactionRules);return ctx.reply(rows.length?rows.map(([w,e])=>`${w} → ${e}`).join('\n'):'No reaction rules.');}if(action==='del'){delete ctx.sessionSettings.reactionRules[String(ctx.args[1]||'').toLowerCase()];await db.save();return ctx.reply('Reaction rule removed.');}if(action==='add'){const word=safeText(ctx.args[1],50).toLowerCase();const emoji=safeText(ctx.args[2],16);if(!word||!emoji)return ctx.reply(`Usage: ${ctx.prefix}reactword add love ❤️`);ctx.sessionSettings.reactionRules[word]=emoji;await db.save();return ctx.reply(`Reaction rule: ${word} → ${emoji}`);}return ctx.reply(`Usage: ${ctx.prefix}reactword add|del|list`);} });
registerCommand({ name:'menutheme', aliases:['menustyle'], category:'owner', ownerOnly:true, description:'Choose WhatsApp menu theme: royal, neon, minimal', usage:'menutheme neon', async run(ctx){const t=String(ctx.args[0]||'').toLowerCase();if(!['royal','neon','minimal'].includes(t))return ctx.reply(`Usage: ${ctx.prefix}menutheme royal|neon|minimal`);ctx.sessionSettings.menuTheme=t;await db.save();await ctx.reply(`🎨 Menu theme: ${t.toUpperCase()}`);} });
registerCommand({ name:'owneralerts', category:'owner', ownerOnly:true, description:'Toggle owner inbox alerts for session/runtime issues', usage:'owneralerts on|off', async run(ctx){const v=String(ctx.args[0]||'').toLowerCase();if(!['on','off'].includes(v))return ctx.reply(`Usage: ${ctx.prefix}owneralerts on|off`);ctx.sessionSettings.ownerAlerts=v==='on';await db.save();await ctx.reply(`🔔 Owner alerts: ${v.toUpperCase()}`);} });

function isPrivateIp(ip){if(net.isIP(ip)===4){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||p[0]===0;}if(net.isIP(ip)===6){const v=ip.toLowerCase();return v==='::1'||v==='::'||v.startsWith('fe80:')||v.startsWith('fc')||v.startsWith('fd');}return true;}
async function assertPublicUrl(raw){let u;try{u=new URL(String(raw));}catch{throw new Error('Provide a valid absolute URL.');}if(!['http:','https:'].includes(u.protocol))throw new Error('Only http/https URLs are supported.');if(/(^|\.)localhost$/i.test(u.hostname)||u.hostname.endsWith('.local'))throw new Error('Local/internal URLs are blocked.');if(net.isIP(u.hostname)){if(isPrivateIp(u.hostname))throw new Error('Private/internal IP URLs are blocked.');}else{const rows=await dns.lookup(u.hostname,{all:true});if(!rows.length||rows.some(r=>isPrivateIp(r.address)))throw new Error('Private/internal destination is blocked.');}return u;}
async function redirectChain(raw){let u=await assertPublicUrl(raw);const chain=[u.toString()];let status=null;for(let i=0;i<6;i++){const r=await fetch(u,{method:'HEAD',redirect:'manual',headers:{'user-agent':`A-X-HK/${config.version}`},signal:AbortSignal.timeout(10000)});status=r.status;const loc=r.headers.get('location');if(!loc||status<300||status>=400)return {chain,status,type:r.headers.get('content-type')||'',length:r.headers.get('content-length')||''};u=await assertPublicUrl(new URL(loc,u).toString());chain.push(u.toString());}return {chain,status,type:'',length:''};}
registerCommand({ name:'checklink', aliases:['linkcheck'], category:'security', description:'Safely inspect a public URL without opening it in your browser', usage:'checklink https://example.com', cooldown:4, async run(ctx){const d=await redirectChain(ctx.argText.trim());const last=d.chain.at(-1);await ctx.reply(`🔎 *LINK CHECK*\nStatus: ${d.status||'-'}\nRedirects: ${d.chain.length-1}\nFinal host: ${new URL(last).hostname}\nType: ${d.type||'-'}\nSize: ${d.length?fmtBytes(d.length):'-'}\nHTTPS: ${last.startsWith('https://')?'YES':'NO'}`);} });
registerCommand({ name:'redirects', aliases:['redirectchain','shortlinkinfo'], category:'security', description:'Show the redirect chain for a safe public URL', usage:'redirects https://bit.ly/...', cooldown:4, async run(ctx){const d=await redirectChain(ctx.argText.trim());await ctx.reply(`🔗 *REDIRECT CHAIN*\n\n${d.chain.map((x,i)=>`${i}. ${x}`).join('\n').slice(0,3600)}\n\nFinal status: ${d.status||'-'}`);} });

registerCommand({ name:'currency', aliases:['fx','convertcurrency'], category:'search', description:'Convert currencies using a live public exchange-rate service', usage:'currency 100 USD PKR', cooldown:4, async run(ctx){const amount=Number(ctx.args[0]);const from=String(ctx.args[1]||'').toUpperCase(),to=String(ctx.args[2]||'').toUpperCase();if(!Number.isFinite(amount)||!/^[A-Z]{3}$/.test(from)||!/^[A-Z]{3}$/.test(to))return ctx.reply(`Usage: ${ctx.prefix}currency 100 USD PKR`);const r=await fetch(`https://api.frankfurter.app/latest?amount=${encodeURIComponent(amount)}&from=${from}&to=${to}`,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Currency service returned ${r.status}`);const d=await r.json();const value=d.rates?.[to];if(!Number.isFinite(value))throw new Error('Currency pair unavailable.');await ctx.reply(`💱 ${amount} ${from} = ${value} ${to}\nRate date: ${d.date||'-'}`);} });
registerCommand({ name:'citytime', aliases:['timecity'], category:'search', description:'Show current time for a city', usage:'citytime Dubai', cooldown:3, async run(ctx){const city=safeText(ctx.argText,100);if(!city)return ctx.reply(`Usage: ${ctx.prefix}citytime Dubai`);const r=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(city)}&count=1&language=en&format=json`,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error('City lookup failed.');const d=await r.json(),row=d.results?.[0];if(!row?.timezone)return ctx.reply('City/timezone not found.');const now=new Intl.DateTimeFormat('en-GB',{timeZone:row.timezone,dateStyle:'full',timeStyle:'long'}).format(new Date());await ctx.reply(`🕒 ${row.name}${row.country?`, ${row.country}`:''}\n${row.timezone}\n${now}`);} });
registerCommand({ name:'emi', aliases:['loan'], category:'productivity', description:'Estimate equal monthly loan payment', usage:'emi 100000 12 24', async run(ctx){const principal=Number(ctx.args[0]),annual=Number(ctx.args[1]),months=Number(ctx.args[2]);if(!Number.isFinite(principal)||principal<=0||!Number.isFinite(annual)||annual<0||!Number.isInteger(months)||months<1)return ctx.reply(`Usage: ${ctx.prefix}emi 100000 12 24`);const r=annual/1200;const payment=r===0?principal/months:principal*r*Math.pow(1+r,months)/(Math.pow(1+r,months)-1);await ctx.reply(`🏦 EMI estimate\nMonthly: ${payment.toFixed(2)}\nTotal: ${(payment*months).toFixed(2)}\nInterest: ${(payment*months-principal).toFixed(2)}`);} });

function contactVcard(name,number){const digits=String(number||'').replace(/\D/g,'');return `BEGIN:VCARD\nVERSION:3.0\nFN:${safeText(name,80)}\nTEL;TYPE=CELL:+${digits}\nEND:VCARD`;}
registerCommand({ name:'vcard', aliases:['savecontact'], category:'utility', description:'Create and send a contact card/VCF', usage:'vcard Ali | 923001234567', async run(ctx){const [name,num]=ctx.argText.split('|').map(x=>x.trim());const digits=String(num||'').replace(/\D/g,'');if(!name||digits.length<8)return ctx.reply(`Usage: ${ctx.prefix}vcard Ali | 923001234567`);const vcard=contactVcard(name,digits);await ctx.send({contacts:{displayName:name,contacts:[{vcard}]}},{quoted:ctx.msg});} });
registerCommand({ name:'contactinfo', category:'utility', description:'Read basic info from a quoted WhatsApp contact card', usage:'contactinfo (reply to contact)', async run(ctx){const q=contextInfo(ctx.msg)?.quotedMessage;const m=unwrapMessage(q||{});const c=m.contactMessage;if(!c)return ctx.reply('Reply to a contact card.');const nums=[...String(c.vcard||'').matchAll(/TEL[^:]*:([^\n\r]+)/gi)].map(x=>x[1].trim());await ctx.reply(`👤 Contact\nName: ${c.displayName||'-'}\nPhone: ${nums.join(', ')||'-'}`);} });

registerCommand({ name:'xpmode', aliases:['xp'], category:'group', groupOnly:true, adminOnly:true, description:'Toggle group XP/levels', usage:'xpmode on|off', async run(ctx){const v=String(ctx.args[0]||'').toLowerCase();if(!['on','off'].includes(v))return ctx.reply(`Usage: ${ctx.prefix}xpmode on|off`);ctx.groupSettings.xpEnabled=v==='on';await db.save();await ctx.reply(`🏆 Group XP: ${v.toUpperCase()}`);} });
registerCommand({ name:'rank', aliases:['level'], category:'group', groupOnly:true, description:'Show your group XP rank', async run(ctx){const row=db.xpBucket(ctx.sessionId,ctx.chat,ctx.sender);const level=Math.floor(Math.sqrt((row.xp||0)/25))+1;const all=Object.entries(db.data.groupXp).filter(([k])=>k.startsWith(`${ctx.sessionId}::${ctx.chat}:`)).map(([k,v])=>({k,xp:v.xp||0})).sort((a,b)=>b.xp-a.xp);const pos=all.findIndex(x=>x.k.endsWith(`:${ctx.sender}`))+1;await ctx.reply(`🏆 *YOUR RANK*\nLevel: ${level}\nXP: ${row.xp||0}\nMessages: ${row.messages||0}\nRank: #${pos||'-'}`);} });
registerCommand({ name:'leaderboard', aliases:['topxp'], category:'group', groupOnly:true, description:'Show top group XP members', async run(ctx){const prefix=`${ctx.sessionId}::${ctx.chat}:`;const rows=Object.entries(db.data.groupXp).filter(([k])=>k.startsWith(prefix)).map(([k,v])=>({jid:k.slice(prefix.length),xp:v.xp||0})).sort((a,b)=>b.xp-a.xp).slice(0,10);if(!rows.length)return ctx.reply('No XP data yet. Ask an admin to enable .xpmode on.');const mentions=rows.map(r=>r.jid);await ctx.send({text:`🏆 *LEADERBOARD*\n\n${rows.map((r,i)=>`${i+1}. @${r.jid.split('@')[0]} • ${r.xp} XP`).join('\n')}`,mentions},{quoted:ctx.msg});} });

registerCommand({ name:'health', aliases:['diagnostic'], category:'system', description:'Show runtime, memory, storage, session and error health', cooldown:5, async run(ctx){let disk='unavailable';try{const st=await fs.statfs(config.persistentRoot);disk=`${fmtBytes(Number(st.bavail)*Number(st.bsize))} free / ${fmtBytes(Number(st.blocks)*Number(st.bsize))}`;}catch{}const mem=process.memoryUsage();await ctx.reply(`🩺 *A-X-HK HEALTH*\nStatus: ONLINE\nVersion: ${config.version}\nNode: ${process.version}\nUptime: ${Math.floor(process.uptime()/60)} min\nRSS: ${fmtBytes(mem.rss)}\nHeap: ${fmtBytes(mem.heapUsed)}\nSystem RAM: ${fmtBytes(os.freemem())} free / ${fmtBytes(os.totalmem())}\nDisk: ${disk}\nCommands: ${db.data.metrics.commandsRun||0}\nErrors: ${db.data.metrics.commandErrors||0}\nSessions known: ${Object.keys(db.data.linkedSessions||{}).length+1}`);} });

registerCommand({ name:'backup', aliases:['safebackup'], category:'owner', ownerOnly:true, description:'Send a safe settings backup that excludes WhatsApp credentials/admin secrets/vault data', async run(ctx){const safe={version:config.version,createdAt:new Date().toISOString(),sessions:db.data.sessions,groups:db.data.groups,users:db.data.users,warnings:db.data.warnings,notes:db.data.notes,sessionAutoReplies:db.data.sessionAutoReplies,reminders:db.data.reminders,birthdays:db.data.birthdays,events:db.data.events,sessionSavedReplies:db.data.sessionSavedReplies,groupXp:db.data.groupXp,sessionPolicy:db.data.sessionPolicy,ui:db.data.ui};const buf=Buffer.from(JSON.stringify(safe,null,2));await ctx.send({document:buf,mimetype:'application/json',fileName:`A-X-HK-safe-backup-${Date.now()}.json`,caption:'🔐 Safe backup • WhatsApp credentials, dashboard auth and encrypted vault data are excluded.'},{quoted:ctx.msg});} });

registerCommand({ name:'autocleanup', category:'owner', ownerOnly:true, description:'Toggle automatic cleanup of stale temporary downloader files', usage:'autocleanup on|off', async run(ctx){const v=String(ctx.args[0]||'').toLowerCase();if(!['on','off'].includes(v))return ctx.reply(`Usage: ${ctx.prefix}autocleanup on|off`);ctx.sessionSettings.autoCleanup=v==='on';await db.save();await ctx.reply(`🧹 Auto cleanup: ${v.toUpperCase()}`);} });
registerCommand({ name:'analytics', aliases:['botanalytics'], category:'owner', ownerOnly:true, description:'Show a compact local usage analytics summary', async run(ctx){const m=db.data.metrics||{};const top=Object.entries(m.commandsByName||{}).sort((a,b)=>b[1]-a[1]).slice(0,8);const today=m.daily?.[new Date().toISOString().slice(0,10)]||{};await ctx.reply(`📊 *A-X-HK ANALYTICS*\n\nMessages: ${m.messagesSeen||0}\nCommands: ${m.commandsRun||0}\nErrors: ${m.commandErrors||0}\nToday: ${today.messages||0} msg • ${today.commands||0} cmd\n\n*Top commands*\n${top.length?top.map(([n,c],i)=>`${i+1}. .${n} • ${c}`).join('\n'):'No command data yet.'}`);} });
registerCommand({ name:'updateinfo', aliases:['buildinfo'], category:'system', description:'Show current A-X-HK build/runtime information', async run(ctx){await ctx.reply(`🧩 *A-X-HK BUILD INFO*\nVersion: ${config.version}\nNode: ${process.version}\nPlatform: ${process.platform}\nMenu theme: ${ctx.sessionSettings.menuTheme||'royal'}\nPersistent data: enabled`);} });
registerCommand({ name:'ship', aliases:['shipmeter'], category:'fun', description:'Harmless friendship/ship compatibility meter', usage:'ship Ali | Sara', async run(ctx){const raw=ctx.argText.trim();const [a,b]=raw.split('|').map(x=>safeText(x,60));if(!a||!b)return ctx.reply(`Usage: ${ctx.prefix}ship Ali | Sara`);const digest=crypto.createHash('sha256').update([a.toLowerCase(),b.toLowerCase()].sort().join('|')).digest();const score=digest.readUInt16BE(0)%101;const bar='█'.repeat(Math.round(score/10))+'░'.repeat(10-Math.round(score/10));await ctx.reply(`💞 *SHIP METER*\n${a} × ${b}\n\n${bar} ${score}%\n\nFor fun only ✨`);} });
